config/routes.rb
Rails.application.routes.draw do
    resources :adoptions
    resources :users
    resources :locations
    resources :foods
    resources :notes
    resources :donations
    resources :trees

end

app/models/tree.rb
class Tree < ActiveRecord::Base
  belongs_to :food
  has_many :adoptions
  has_many :users, through: :adoptions
  has_many :notes
  has_many :donations
  has_many :locations, through: :donations

  scope :public_trees, lambda { where("public = true") }
  scope :alive, lambda { where("dead = false") }
  scope :not_farm, lambda { where('id > -1') }
  scope :adopted, lambda { joins(:adoptions) }
  scope :in_season, lambda { where(:food_id => Food.pickable.in_season) }
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  # before_action :set_tree, only: [:show, :edit, :update, :destroy]

  # GET /trees
  # GET /trees.json
  # Used for filtering
  def index
    # XXX catch errors
    # XXX verify json response
    if current_user.try(:is_privileged?)
      @trees = Tree.alive
    else
      @trees = Tree.public_trees.alive.not_farm
    end

    food_ids = session[:food_ids].split(/,/)

    # if (isset($_SESSION['temp_trees']) && $_SESSION['temp_trees'] != null) {
    #   $sql .= "OR `id` IN (" . $_SESSION['temp_trees'] . ") ";
    # }
  end

  # GET /trees/1
  # GET /trees/1.json
  # Used for fetching a single tree
  def show
    # XXX catch errors
    # XXX verify json response
    if current_user.try(:is_privileged?)
      @tree = Tree.alive.find(tree_params[:id])
    else
      @tree = Tree.public_trees.alive.not_farm.find(tree_params[:id])
    end

    # if (isset($_SESSION['temp_trees']) && $_SESSION['temp_trees'] != null) {
    #   $sql .= "OR `id` IN (" . $_SESSION['temp_trees'] . ") ";
    # }

  end

  # GET /trees/new
  # def new
  #   @tree = Tree.new
  # end

  # GET /trees/1/edit
  # def edit
  # end

  # POST /trees
  # POST /trees.json
  def create
  # XXX catch errors
  # XXX verify json response
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        # format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render :show, status: :created, location: @tree }
      else
        # format.html { render :new }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    # XXX catch errors
    # XXX verify json response
    respond_to do |format|
      if @tree.update(tree_params)
        # format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree }
      else
        # format.html { render :edit }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  # def destroy
  #   @tree.destroy
  #   respond_to do |format|
  #     format.html { redirect_to trees_url, notice: 'Tree was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.fetch(:tree, {}).permit(:id, :lat, :lng, :food, :description, :address, :public, :dead, :owner, :parent
        :rating)
    end
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_form.html.erb
<%= form_for(@tree) do |f| %>
  <% if @tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% @tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing Tree</h1>

<%= render 'form' %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= link_to 'Show', tree %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
        <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree', new_tree_path %>

app/views/trees/new.html.erb
<h1>New Tree</h1>

<%= render 'form' %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>